In [ ]:
import sys
import os

sys.path.append(os.path.abspath(".."))

import pandas as pd
import numpy as np

from src.cleaning import clean_transactions

from src.merchant_extraction import (
    load_merchant_map,
    cleanup_description,
    normalize_merchant
)


from src.eda import (
    spending_by_category,
    average_monthly_spending_by_category,
    spending_by_merchant,
    average_monthly_spending_by_merchant,
    monthly_spending,
    average_monthly_spending
)

from src.visualization import (
    plot_avg_monthly_spend_by_merchant,
    plot_monthly_spending,
    plot_average_spend_by_month,
    plot_top_merchants_last_12_months,
    plot_top_merchants_by_category
)

In [2]:
df = clean_transactions(
    "../data/Discover_Transaction_History.csv"
)

print(f"Transactions: {len(df):,}")

df.head()

Transactions: 3,286

/Users/mafphd/personalprojects/src/cleaning.py:53: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["trans_date"] = pd.to_datetime(
/Users/mafphd/personalprojects/src/cleaning.py:59: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["post_date"] = pd.to_datetime(

,trans_date,post_date,description,amount,category,desc_clean,month,day_of_week,is_weekend
0,2023-10-17,2023-10-19,WALGREENS #10196 WAUWATOSA WI,13.70,Merchandise,WALGREENS WAUWATOSA WI,2023-10,Tuesday,False
1,2023-10-18,2023-10-19,5-365 FOOD SERVICE TROY MI,3.05,Restaurants,FOOD SERVICE TROY MI,2023-10,Wednesday,False
2,2023-10-18,2023-10-19,QUALITY HEATING AND SHEE BROOKFIELD WI,79.65,Services,QUALITY HEATING AND SHEE BROOKFIELD WI,2023-10,Wednesday,False
3,2023-10-18,2023-10-19,SOMMER'S INC. MEQUON WI649149,114.59,Automotive,SOMMER S INC MEQUON WI649149,2023-10,Wednesday,False
4,2023-10-19,2023-10-19,MILTOWN EATS LLC 4144349799 WI,30.00,Supermarkets,MILTOWN EATS LLC WI,2023-10,Thursday,False

In [9]:
unique_descriptions = (
    df["description"]
    .dropna()
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

unique_descriptions_df = pd.DataFrame({
    "description": unique_descriptions
})

print(
    f"Unique descriptions: "
    f"{len(unique_descriptions_df):,}"
)

unique_descriptions_df.head()

Unique descriptions: 1,403

                           description
0      #492028TOPPIZTOSA 4142574002 WI
1       #492028TOPPIZTOSA WAUWATOSA WI
2  #5993 VILLA IK MAYFAIR WAUWATOSA WI
3   077 HARDEES SHEBOYGAN SHEBOYGAN WI
4   2LEVY AT FISERV FORUM MILWAUKEE WI

In [10]:
unique_descriptions_df.to_csv(
    "../outputs/unique_descriptions.csv",
    index=False
)

#Use external merchant_lookup.csv file based on unique_descriptions_df

In [6]:
merchant_lookup = pd.read_csv(
    "../data/merchant_lookup.csv"
)

merchant_lookup.head()

,description,merchant_clean,Unnamed: 2,Unnamed: 3
0,#492028TOPPIZTOSA 4142574002 WI,TOPPIZTOSA,NaN,NaN
1,#492028TOPPIZTOSA WAUWATOSA WI,TOPPIZTOSA,NaN,NaN
2,#5993 VILLA IK MAYFAIR WAUWATOSA WI,VILLA IK MAYFAIR,NaN,NaN
3,077 HARDEES SHEBOYGAN SHEBOYGAN WI,HARDEE'S,NaN,NaN
4,2LEVY AT FISERV FORUM MILWAUKEE WI,LEVY AT FISERV FORUM,NaN,NaN

In [25]:
merchant_lookup = merchant_lookup[["description", "merchant_clean"]]

analysis_df = df.merge(
    merchant_lookup,
    on="description",
    how="left"
)

analysis_df.head()

,trans_date,post_date,description,amount,category,desc_clean,month,day_of_week,is_weekend,merchant_clean
0,2023-10-17,2023-10-19,WALGREENS #10196 WAUWATOSA WI,13.70,Merchandise,WALGREENS WAUWATOSA WI,2023-10,Tuesday,False,WALGREENS
1,2023-10-18,2023-10-19,5-365 FOOD SERVICE TROY MI,3.05,Restaurants,FOOD SERVICE TROY MI,2023-10,Wednesday,False,365 FOOD SERVICE
2,2023-10-18,2023-10-19,QUALITY HEATING AND SHEE BROOKFIELD WI,79.65,Services,QUALITY HEATING AND SHEE BROOKFIELD WI,2023-10,Wednesday,False,QUALITY HEATING & SHEET METAL
3,2023-10-18,2023-10-19,SOMMER'S INC. MEQUON WI649149,114.59,Automotive,SOMMER S INC MEQUON WI649149,2023-10,Wednesday,False,SOMMER'S
4,2023-10-19,2023-10-19,MILTOWN EATS LLC 4144349799 WI,30.00,Supermarkets,MILTOWN EATS LLC WI,2023-10,Thursday,False,MILTOWN EATS

In [26]:
analysis_df = analysis_df[analysis_df['merchant_clean'] != 'APPLIANCE GALLERY']
analysis_df.head()

,trans_date,post_date,description,amount,category,desc_clean,month,day_of_week,is_weekend,merchant_clean
0,2023-10-17,2023-10-19,WALGREENS #10196 WAUWATOSA WI,13.70,Merchandise,WALGREENS WAUWATOSA WI,2023-10,Tuesday,False,WALGREENS
1,2023-10-18,2023-10-19,5-365 FOOD SERVICE TROY MI,3.05,Restaurants,FOOD SERVICE TROY MI,2023-10,Wednesday,False,365 FOOD SERVICE
2,2023-10-18,2023-10-19,QUALITY HEATING AND SHEE BROOKFIELD WI,79.65,Services,QUALITY HEATING AND SHEE BROOKFIELD WI,2023-10,Wednesday,False,QUALITY HEATING & SHEET METAL
3,2023-10-18,2023-10-19,SOMMER'S INC. MEQUON WI649149,114.59,Automotive,SOMMER S INC MEQUON WI649149,2023-10,Wednesday,False,SOMMER'S
4,2023-10-19,2023-10-19,MILTOWN EATS LLC 4144349799 WI,30.00,Supermarkets,MILTOWN EATS LLC WI,2023-10,Thursday,False,MILTOWN EATS

In [27]:
pd.set_option("display.max_rows", 100)
merchant_review = (
    analysis_df
    .groupby("merchant_clean")
    .agg(
        transaction_count=("amount", "count"),
        total_spend=("amount", "sum"),
        sample_description=("description", "first")
    )
    .reset_index()
    .sort_values(
        "total_spend",
        ascending=False
    )
)

display(
    merchant_review.head(100)
)

,merchant_clean,transaction_count,total_spend,sample_description
86,CENTRAL BARK,189,8127.07,CENTRAL BARK-BROOKFIELD 262-781-5554 WI
303,LEGACY GYM MKE,75,7065.40,LEGACY GYM MKE 262-989-6696 WI
10,AAA INSURANCE,7,5095.03,AAA INSURANCE GW EFT 800-222-6424 MI
479,SENDIK'S,131,4717.82,SENDIK'S WAUWATOSA WAUWATOSA WIAPPLE PAY ENDIN...
355,MILTOWN EATS,90,4436.98,MILTOWN EATS LLC 4144349799 WI
276,JULIE'S PARK CAFE & MOTEL,6,3955.48,JULIES PARK CAFE & MOTEL FISH CREEK WI
342,METCALFE'S MARKET,47,3241.84,METCALFE MARKET TOSA WAUWATOSA WI
25,AMTRAK,8,3204.25,AMTRAK MOBILE 202-906-3000 DCAPPLE PAY ENDING ...
503,SOMMER'S AUTOMOTIVE,2,3138.67,SOMMER'S AUTOMOTIVE - 262-242-0100 WI173412795...
359,MILWAUKEE ELECTRIC TOOL,10,2819.33,SQ *MILWAUKEE ELECTRIC BROOKFIELD WI0002305843...
508,SPECTRUM,31,2713.77,SPECTRUM 855-707-7328 MORC807386179
623,WAUWATOSA SCHOOL OF MUSIC,24,2533.00,WAUWATOSA SCHOOL OF MUSI WAUWATOSA WI
455,RIGHT AT SCHOOL,16,2295.00,RIGHT AT SCHOOL 8552872466 IL
463,SALON MARIE,32,2204.01,SALON MARIE LLC HALES CORNERSWI
315,LOVE YOUR FACE SKINCARE,8,2196.25,PP*LOVE YOUR FACE SKINCA WAUWATOSA WI
230,HAPPY BUDDHA BOUTIQUE,26,2090.76,SQ *HAPPY BUDDHA BOUTI MILWAUKEE WI00023058430...
576,TOSA WELLNESS,8,2004.35,GLOSS* TOSA WELLNESS & 8557702098 WI
280,KETTLE RANGE MEATS,45,1886.41,PY *KETTLE RANGE MEAT CO MILWAUKEE WI
143,DISCOVERY WORLD,6,1837.27,DISCOVERY WORLD 4147651977 WI
405,OPEN HEARTH LODGE,7,1830.36,BL - OPEN HEARTH LODGE SISTER BAY WI
391,NOODLES & COMPANY,60,1813.03,ORDER.NOODLES.COM 2122600895 CO
140,DINING FURNITURE SHOWCASE,2,1531.46,DINING FURNITURE SHOWCAS WEST ALLIS WI
62,BIRCH LIVING,1,1487.90,SP BIRCH LIVING 8883300781 NY
102,CLUB SCIKIDZ,2,1479.50,ACT*CLUB SCIKIDZ LLC 8006634991 TX
92,CHEWY,20,1405.15,PAYPAL *CHEWY INC 402-935-7733 CA
598,UNIVERSITY OF WISCONSIN MILWAUKEE,2,1398.40,UWM SCE 414-2273200 WI
434,POCO PIZZA,11,1336.39,SP POCO PIZZA 9209482878 WI
4,365 FOOD SERVICE,370,1314.02,5-365 FOOD SERVICE TROY MI
400,NOURISH NATURAL PRODUCTS,23,1309.33,SP NOURISH NATURAL P 4142310955 WI
178,EVERVET,9,1299.27,EVERVET WAUWATOSA WI
461,RUCKUS & GLEE,18,1280.83,LS RUCKUS & GLEE 4143953201 WI
197,FROEDTERT HEALTH,19,1206.89,MED*FROEDTERT HEALTH I 800-803-8155 WI202907443
502,SOMMER'S,4,1189.67,SOMMER'S INC. MEQUON WI649149
366,MISS MOLLY'S CAFE,38,1122.90,TST* MISS MOLLYS CAFE 414-249-5665 WIAPPLE PAY...
207,GILLES FROZEN CUSTARD,31,1086.62,GILLES FROZEN CUSTARD MILWAUKEE WI
128,CULVER'S,46,1073.69,CULVERS OF WEST ALLIS WEST ALLIS WI
168,ELEKTRA LIGHTS & FANS,3,1040.91,ELEKTRA LIGHTS & FANS WAUWATOSA WI
452,REI,14,1020.24,REI #60 BROOKFIELD BROOKFIELD WI4544190600010240
183,FIDDLEHEADS COFFEE,43,1019.59,FIDDLEHEADS COFFEE ROAST WAUWATOSA WI
442,QUALITY HEATING & SHEET METAL,7,960.72,QUALITY HEATING AND SHEE BROOKFIELD WI
126,CROSSWAYS CAMPING,4,940.00,RF *CROSSWAYS CAMPIN 920-882-0023 WI
448,RAY'S WINE & SPIRITS,19,878.05,RAY'S WINE AND SPIRITS WAUWATOSA WIAPPLE PAY E...
572,TOSA DENTAL,5,865.00,TOSA DENTAL LLC WAUWATOSA WI
80,CAFE HOLLANDER,20,859.08,CAFE HOLLANDER W STATE WAUWATOSA WI
93,CHICK-FIL-A,36,839.30,CHICK-FIL-A #04377 MENOMONEE FALWI
647,ZOOLOGICAL SOCIETY OF MILWAUKEE,4,816.80,ZOOLOGICAL SOCIETY OF MI MILWAUKEE WI
103,COLECTIVO COFFEE,34,802.29,COLECTIVO COFFEE ROAST 4142733747 WIAPPLE PAY ...
30,AR WORKSHOP,2,800.00,AR BROOKFIELD 5413165747 WI
453,RENARD'S CHEESE,10,773.34,RENARDS CHEESE STURGEON BAY WI
412,PANERA BREAD,29,770.34,PANERA BREAD #601550 O 262-834-9999 WIAPPLE PA...
332,MARQUETTE UNIVERSITY,2,750.00,MARQUETTE UNIVERSITY 8333000190 WI
162,DSW,12,735.73,DSW INC. 614-237-7100 OHAPPLE PAY ENDING IN 7049
263,INNLET MOTEL,2,703.56,INNLET MOTEL STURGEON BAY WI
60,BENTLEY'S PET STUFF,12,691.13,LS BENTLEYS PET STUFF 2245674700 WI
348,MIDTOWN GRILL,17,681.66,TST* MIDTOWN GRILL 414-837-6400 WIAPPLE PAY EN...
634,WILSON CENTER,1,680.00,WILSON CENTER 2627819470 WIAPPLE PAY ENDING IN...
376,MURF'S FROZEN CUSTARD,19,660.59,MURFSFROZENCUSTARDONLINE BROOKFIELD WI
515,SPRINGHILL SUITES BY MARRIOTT,2,634.58,SPRINGHILL SUITES BY MAR 4123239005 PA
28,APPLE,17,630.87,APPLE.COM/US 800-676-2775 CAW1344816685A1
296,LANDMARK RESORT,2,597.53,LANDMARK RESORT RENTAL 920-868-3205 WI
557,THE THIRSTY COW TAPHOUSE,4,595.39,THE THIRSTY COW TAPHOUSE BAILEYS HARBOWI
69,BOSWELL BOOK COMPANY,13,579.88,BOSWELL BOOK COMPANY MILWAUKEE WI
77,BUCKATABON TAVERN,5,577.87,BUCKATABON TAVERN WAUWATOSA WI
273,JOY ICE CREAM SOCIAL,30,573.05,SQ *JOY ICE CREAM SOCI WAUWATOSA WI00023058430...
66,BLUES EGG,13,563.85,TST* BLUES EGG MILWAUKEE WI00091966017899928019AA
51,BASECAMP BOULDER,1,555.10,BASECAMP BOULDER BOULDER CO
552,THE REAL GOOD LIFE,7,554.39,SP THE REAL GOOD LIFE 2624215751 WI
97,CHIPOTLE,17,550.92,CHIPOTLE ONLINE 949-524-4000 CA
565,THRIVE CAUSEMETICS,7,549.06,THRIVECAUSEMETICS 8888044318 WAAPPLE PAY ENDIN...
645,YMCA OF GREATER WAUKESHA,3,548.00,YMCA OF GREATER WAUKESHA 262-542-2557 WI
53,BB'S ON NORTH,9,539.23,TST* BB'S ON NORTH WAUWATOSA WI
139,DICK'S SPORTING GOODS,10,523.03,DICKS SPORTING GOODS WAUWATOSA TN
147,DISNEY PLUS,3,518.32,DISNEY PLUS 8889057888 CA
314,LOVE YOUR FACE,2,500.94,GLOSS* LOVE YOUR FACE 8557702098 WI
633,WILDE TOYOTA,1,500.00,WILDE TOYOTA WEST ALLIS WI
625,WEIGHLESS MD,1,499.00,WEIGHLESS MD BROOKFIELD WI
408,OUTPOST NATURAL FOODS,8,493.11,OUTPOST NATURAL FOODS CO WAUWATOSA WI
574,TOSA REC,6,478.25,VSI*TOSAREC ONLINE 414-773-2905 WIVSI*TOSAREC ...
211,GIRL SCOUTS OF WISCONSIN SOUTHEAST,7,475.00,GS WISCONSIN SOUTHEAST 800-565-4475 WI
115,COURTYARD BY MARRIOTT,1,474.71,COURTYARD BY MARRIOTT CH CHICAGO IL
54,BE BEAUTY,4,464.51,SQ *BE BEAUTY EGG HARBOR WI0002305843020410601803
446,RAISING CANE'S,17,463.47,RAISING CANES 0948 BROOKFIELD WI02417P
501,SOMERSET INN & SUITES,1,462.50,SOMERSET INN AND SUITES EPHRAIM WI
328,MARKEL PERSONAL LINES,3,462.00,MARKEL PERSONAL LINES 800-236-2453 WI
422,PETS BEST,1,459.25,PETS BEST INSURANCE SERV 877-738-7237 FL
603,VALENTINE COFFEE,24,453.56,TST* VALENTINE COFFEE MILWAUKEE WI000376900145...
113,CORP CHARITY GIVING,1,450.00,CORP CHARITY GIVING 8667516031 SC
14,ADVENTURE ROCK,1,435.00,ADVENTURE ROCK BKF 262-790-6800 WI
595,ULTIMATE NINJAS,2,420.00,ULTIMATE NINJAS OAK CREE 414-307-4411 WI
32,ARTE WINE AND PAINTING,2,418.63,ARTE WINE AND PAINTING S 4147362302 WI
347,MICROSOFT,31,415.03,MICROSOFT#G033377924 MSBILL.INFO WA
513,SPOT PET INSURANCE,1,412.08,SPOT PET 8009051595 WA
61,BIG WHITE YETI,10,411.03,SQ *BIG WHITE YETI MILWAUKEE WI000230584301874...
482,SHADY LANE GREENHOUSES,2,407.41,SHADY LANE GREENHOUSES MENOMONEE FALWI
577,TOSA WELLNESS SPA,1,402.00,SP TOSA WELLNESS SPA WAUWATOSA WI
338,MCKINLEY ELEMENTARY PTO,6,397.41,MCKINLEY ELEM PTO 4144433570 WI
19,AMAZON,9,391.47,AMZN MKTP US*9L1E121N3 AMZN.COM/BILLWA3INV5NEQMRS
490,SIENA RETREAT CENTER,1,390.00,PY *SIENA RETREAT CENTER RACINE WIAPPLE PAY EN...
564,THIRDLOVE,4,380.69,PAYPAL *THIRDLOVE 888-221-1161 CA
5,365 MARKET,142,376.64,365 MARKET K 888 432-329 TROY MI

In [ ]:
# --------------------------------------------------
# Merchant Summary
# --------------------------------------------------

total_months = (
    analysis_df["month"]
    .nunique()
)

merchant_summary = (
    analysis_df
    .groupby("merchant_clean")
    .agg(
        transaction_count=("amount", "count"),
        active_months=("month", "nunique"),
        total_spend=("amount", "sum"),
        average_transaction=("amount", "mean")
    )
    .reset_index()
)

# Average spend across ALL months in analysis period
merchant_summary["avg_monthly_spend"] = (
    merchant_summary["total_spend"]
    / total_months
)

# Fraction of months merchant appears
merchant_summary["monthly_frequency"] = (
    merchant_summary["active_months"]
    / total_months
)

merchant_summary = (
    merchant_summary
    .sort_values(
        "avg_monthly_spend",
        ascending=False
    )
)

display(
    merchant_summary.head(50)
)

In [ ]:
plot_avg_monthly_spend_by_merchant(
    merchant_summary,
    top_n=20
)

In [ ]:
monthly_totals = (
    analysis_df
    .groupby("month")["amount"]
    .sum()
    .reset_index(
        name="monthly_spend"
    )
)

In [ ]:
plot_monthly_spending(
    monthly_totals
)

In [ ]:
plot_average_spend_by_month(
    analysis_df
)

In [ ]:
plot_top_merchants_last_12_months(
    analysis_df,
    top_n=20
)

In [ ]:
plot_top_merchants_by_category(
    analysis_df,
    top_n=20
)

In [ ]:
from src.visualization import (
    plot_merchant_frequency_vs_spend
)

plot_merchant_frequency_vs_spend(
    merchant_summary,
    min_monthly_spend=20,
    top_n_labels=30
)