In [12]:
import sys
import os

# Add project root to Python path
sys.path.append(os.path.abspath(".."))

In [3]:
import pandas as pd

from src.cleaning import load_data, standardize_column_names, convert_dates, clean_amount, clean_transactions
from src.fuzzy_grouping import group_merchants

In [3]:
df = load_data("../data/Discover_Transaction_History.csv")
df = standardize_column_names(df)
df = convert_dates(df)
df = clean_amount(df)

/Users/mafphd/personalprojects/src/cleaning.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["post_date"] = pd.to_datetime(df["post_date"], errors="coerce")

In [6]:
from src.token_profiler import suggest_noise_tokens, get_token_examples
noise_candidates = suggest_noise_tokens(
    df,
    max_token_length=3,
    min_frequency=10
)

noise_candidates.head(20)

     token  count
2       WI   1648
6       MI    547
34      IN    522
32     PAY    511
13       S    284
66      SQ    267
88     TST    188
18     LLC    170
92      AA    146
72      CA    135
46     COM    121
9      AND    113
50      SP    100
23      CO     96
152    MKE     90
147    BAY     78
170    GYM     75
1006     J     71
157      P     70
280      K     65

In [4]:
df = clean_transactions("../data/Discover_Transaction_History.csv")
df = group_merchants(df, threshold=85)

/Users/mafphd/personalprojects/src/cleaning.py:36: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["post_date"] = pd.to_datetime(df["post_date"], errors="coerce")

In [5]:
df[["description", "desc_clean", "merchant_clean"]].sort_values("merchant_clean")

,description,desc_clean,merchant_clean
45,AAA ACG NE0069 EFT RCC 800-222-1134 MI,AAA ACG NE EFT RCC MI,AAA ACG
2483,AAA ACG NE0069 EFT RCC 800-222-1134 MI,AAA ACG NE EFT RCC MI,AAA ACG
1238,AAA ACG NE0069 EFT RCC 800-222-1134 MI,AAA ACG NE EFT RCC MI,AAA ACG
730,AAA INS GW RCCREF DEARBORN MI,AAA INS GW RCCREF DEARBORN MI,AAA INS
17,AAA INSURANCE GW EFT 800-222-6424 MI,AAA INSURANCE GW EFT MI,AAA INSURANCE
...,...,...,...
346,TST* YO MAMA - WAUWATO WAUWATOSA WI00042815015...,YO MAMA WAUWATO WAUWATOSA AA,YO MAMA
935,ZOOLOGICAL SOCIETY OF MI MILWAUKEE WI,ZOOLOGICAL SOCIETY OF MI MILWAUKEE,ZOOLOGICAL SOCIETY
1279,ZOOLOGICAL SOCIETY OF MI MILWAUKEE WI,ZOOLOGICAL SOCIETY OF MI MILWAUKEE,ZOOLOGICAL SOCIETY
893,ZOOLOGICAL SOCIETY OF MI 4142582333 WI,ZOOLOGICAL SOCIETY OF MI,ZOOLOGICAL SOCIETY
394,ZOOLOGICAL SOCIETY OF MI MILWAUKEE WI,ZOOLOGICAL SOCIETY OF MI MILWAUKEE,ZOOLOGICAL SOCIETY

In [5]:
df.groupby("merchant_clean")["description"].unique().head(10)

merchant_clean
AAA ACG                       [AAA ACG NE0069 EFT RCC 800-222-1134 MI]
AAA INS                                [AAA INS GW RCCREF DEARBORN MI]
AAA INSURANCE                   [AAA INSURANCE GW EFT 800-222-6424 MI]
ACE HARDWARE                [ACE HARDWARE CORPORATION 888-827-4223 IL]
ACTCLUB SCIKIDZ                   [ACT*CLUB SCIKIDZ LLC 8006634991 TX]
ADIDAS CHICAGO                        [ADIDAS 6579 CHICAGO CHICAGO IL]
ADVENTURE ROCK                    [ADVENTURE ROCK BKF 262-790-6800 WI]
AGA SERVICE                      [AGA SERVICE COMPANY 800-628-4908 VA]
ALLYS BISTRO                            [ALLYS BISTRO MENOMONEE FALWI]
AMAZON MKTPLAYQRK    [AMAZON MKTPL*AY3Q13RK3 AMZN.COM/BILLWA2YXHR3D...
Name: description, dtype: object

In [6]:
df["merchant_clean"].value_counts().head(10)

merchant_clean
FOOD SERVICE              370
CENTRAL BARKBROOKFIELD    189
SENDIKS WAUWATOSA         159
MARKET K                  134
MILTOWN EATS               90
LEGACY GYM                 75
FIDDLEHEADS COFFEE         43
PY KETTLE                  42
MISS MOLLYS                36
COLECTIVO COFFEE           34
Name: count, dtype: int64

In [10]:
df['merchant_clean'].nunique()

709

In [11]:
df.head()

,trans._date,post_date,description,amount,category,desc_clean,merchant,merchant_clean
0,10/17/23,2023-10-19,WALGREENS #10196 WAUWATOSA WI,13.70,Merchandise,WALGREENS WAUWATOSA,WALGREENS WAUWATOSA,WALGREENS WAUWATOSA
1,10/18/23,2023-10-19,5-365 FOOD SERVICE TROY MI,3.05,Restaurants,FOOD SERVICE TROY MI,FOOD SERVICE TROY MI,FOOD SERVICE
2,10/18/23,2023-10-19,QUALITY HEATING AND SHEE BROOKFIELD WI,79.65,Services,QUALITY HEATING AND SHEE BROOKFIELD,QUALITY HEATING AND SHEE BROOKFIELD,QUALITY HEATING
3,10/18/23,2023-10-19,SOMMER'S INC. MEQUON WI649149,114.59,Automotive,SOMMERS INC MEQUON,SOMMERS INC MEQUON,SOMMERS INC
4,10/19/23,2023-10-19,MILTOWN EATS LLC 4144349799 WI,30.00,Supermarkets,MILTOWN EATS,MILTOWN EATS,MILTOWN EATS